CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "songs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar UNIQUE NOT NULL,
  "duration" float NOT NULL,
  "release_date" integer NOT NULL,
  "album_id" integer NOT NULL
);

CREATE TABLE "artists" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "genre_id" integer UNIQUE NOT NULL
);

CREATE TABLE "playlists" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "albums" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "artist_id" integer NOT NULL,
  "release_date" integer NOT NULL
);

CREATE TABLE "song_to_playlist" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playlist_id" integer NOT NULL,
  "song_id" integer NOT NULL
);

CREATE TABLE "artist_to_song" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" integer NOT NULL,
  "song_id" integer NOT NULL
);

CREATE TABLE "genre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "artist_to_song" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("id");

ALTER TABLE "artist_to_song" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("id");

ALTER TABLE "song_to_playlist" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("id");

ALTER TABLE "playlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "genre" ADD FOREIGN KEY ("id") REFERENCES "artists" ("genre_id");

ALTER TABLE "song_to_playlist" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("id");

ALTER TABLE "songs" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("id");

ALTER TABLE "albums" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("id");
